name = "Save Equipment Slots"
description = "Saves the inventory slots of equipment items and makes sure they always return to their saved slot. If a saved slot is occupied items will be rearranged automatically to make space."
author = "dani"
version = "1.4.2"
forumthread = ""
api_version = 6
api_version_dst = 10

dont_starve_compatible = true
reign_of_giants_compatible = true
shipwrecked_compatible = true
dst_compatible = true

all_clients_require_mod = false
client_only_mod = true

icon_atlas = "modicon.xml"
icon = "modicon.tex"

local disable_save_slot_toggle_options =
{
  { description = "- none -", data = false },

  -- Control + A through Control + Z, generated by a tool as none of Lua's builtin functions are available so cannot do a loop to create it here.
  {description="Control + A",data=97},{description="Control + B",data=98},{description="Control + C",data=99},{description="Control + D",data=100},{description="Control + E",data=101},{description="Control + F",data=102},{description="Control + G",data=103},{description="Control + H",data=104},{description="Control + I",data=105},{description="Control + J",data=106},{description="Control + K",data=107},{description="Control + L",data=108},{description="Control + M",data=109},{description="Control + N",data=110},{description="Control + O",data=111},{description="Control + P",data=112},{description="Control + Q",data=113},{description="Control + R",data=114},{description="Control + S",data=115},{description="Control + T",data=116},{description="Control + U",data=117},{description="Control + V",data=118},{description="Control + W",data=119},{description="Control + X",data=120},{description="Control + Y",data=121},{description="Control + Z",data=122}
}

configuration_options =
{
  {
    name = "enable_previews",
    label = "Slot Previews",
    hover = "Shows a preview of the saved equipment above each inventory slot.\n"..
            "Click a preview to clear the saved slot of that equipment.",

    options = {
      { description = "Enabled", data = true },
      { description = "Disabled", data = false },
    },

    default = true
  },

  {
    name = "allow_equip_for_space",
    label = "Allow Equip For Space",
    hover = "Allows an item to be equipped in order to make space for an incoming item.",
    options = {
      { description = "Enabled", data = true },
      { description = "Disabled", data = false },
    },

    default = true
  },

  {
    name = "reserve_saved_slots",
    label = "Reserve Saved Slots",
    hover = "Determines if saved slots will be reserved for their items\n"..
            "and if this only happens when there are other slots available.",

    options = {
      { description = "If Free Slots", data = "if_free_slots" },
      { description = "Always", data = "always" },
      { description = "Never", data = false },
    },

    default = false
  },

  {
    name = "disable_save_slots_toggle",
    label = "Disable Save Slots Toggle",
    hover = "Key combination that will toggle saving slots on/off.",
    options = disable_save_slot_toggle_options,
    default = false
  },

  {
    name = "save_slots_initial_state",
    label = "Save Slots Initial State",
    hover = "The initial state of the Save Slots behavior.\n"..
            "Only used when a toggle key is configured.",

    options = {
      { description = "On", data = true },
      { description = "Off", data = false },
    },

    default = true
  },

  {
    name = "apply_to_items",
    label = "Apply To Items",
    hover = "Save slots of these item types",

    options = {
      { description = "Equipment", data = "100" },
      { description = "Eq. + Food", data = "110" },
      { description = "Eq. + Healing", data = "101" },
      { description = "Eq. + Fo. + He.", data = "111" },
      { description = "All items", data = "all" },
    },

    default = "100"
  },
}
